/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.developia;

import info.developia.gti.Injector;

public class Launcher {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Injector injector = new Injector();
        injector.add(Library.class);
        Library library = (Library) injector.instances.get("info.developia.Library");
        library.process();
    }
}
