
name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Set up JDK 11
        uses: actions/setup-java
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action
      - name: Create Secret File
        run: |
          echo -n "${{ secrets.GRADLE_PROPERTIES }}" | base64 --decode > ~/.gradle/gradle.properties
          echo -n "${{ secrets.SIGNING_SECRET_KEY_RING_CONTENT }}" | base64 --decode > ~/.gradle/secring.gpg
      - name: Build
        run: ./gradlew build
      - name: Publish Snapshot
        run: ./gradlew publishToSonatype
